thankslist_controller:
    pattern: /thankslist
    defaults: { _controller: gfksx.thanks_for_posts.controller.thankslist:main, mode: "", author_id: 1, give: "", top: 0, start: 0, sort_key: "a", sort_dir: "d", topic_id: 0, return_chars: 300 }

toplist_controller:
    pattern: /toplist
    defaults: { _controller: gfksx.thanks_for_posts.controller.toplist:main, mode: "", start: 0, topic_id: 0, return_chars: 300 }

thanks_for_posts_controller:
    path: /thanks_for_posts/{action}/{poster}/{forum}/{topic}/{post}
    defaults: { _controller: gfksx.thanks_for_posts.thanks_ajax_handler:main }
    requirements:
        post: \d+
        
