services:
    gfksx.ThanksForPosts.listener:
        class: gfksx\ThanksForPosts\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache.driver
            - %core.root_path%
            - %core.php_ext%
            - @gfksx.ThanksForPosts.helper
        tags:
            - { name: event.listener }
    gfksx.ThanksForPosts.helper:
        class: gfksx\ThanksForPosts\core\helper
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache.driver
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
    gfksx.ThanksForPosts.controller.thankslist:
        class: gfksx\ThanksForPosts\controller\thankslist
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache.driver
            - %core.root_path%
            - %core.php_ext%
            - @controller.helper
            - @service_container
            - @request
    gfksx.ThanksForPosts.controller.toplist:
        class: gfksx\ThanksForPosts\controller\toplist
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache.driver
            - %core.root_path%
            - %core.php_ext%
            - @controller.helper
            - @service_container
            - @gfksx.ThanksForPosts.helper
            - @request
